# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
#Import csv data for analysis
cities_pd = pd.read_csv("../Resources/output_data/cities_data.csv")
cities_pd

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Arima,10.6374,-61.2823,76.66,93,20,0.00,TT,1631353324
1,Huliao,24.5032,116.4046,89.24,56,36,3.33,CN,1631353325
2,Leópolis,-23.1978,-50.7958,64.45,73,100,3.06,BR,1631353325
3,Farmington,44.6573,-93.1688,68.09,87,1,0.00,US,1631353327
4,Cecerleg,47.4769,101.4503,44.29,96,100,5.86,MN,1631353328
...,...,...,...,...,...,...,...,...,...
594,Villeurbanne,45.7667,4.8803,73.99,68,20,6.91,FR,1631354076
595,Waldsee,49.3956,8.4406,73.06,75,75,5.75,DE,1631354077
596,Shinfield,51.4080,-0.9470,69.46,81,75,1.99,GB,1631354078
597,Ka Soleil,19.4456,-72.6883,77.16,83,84,4.76,HT,1631354080
598,São João da Boa Vista,-21.9689,-46.7978,62.55,70,98,4.00,BR,1631354081

In [3]:
print(cities_pd.dtypes)

City           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
Country        object
Date            int64
dtype: object

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:
# Store latitude and longitude in locations
#Store humidity in variable
locations = cities_pd[["Lat", "Lng"]]
humidity = cities_pd['Humidity']
max_humidity = (cities_pd['Humidity']).max()

In [5]:
# Plot Heatmap
fig1 = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, max_intensity = max_humidity,   
                                 dissipating=False, point_radius=2)


# Add layer
fig1.add_layer(heat_layer)

# Display figure
fig1

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
cities_pd.describe()

,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Date
count,599.000000,599.000000,599.000000,599.000000,599.000000,599.000000,5.990000e+02
mean,30.447051,-11.721233,70.634775,71.023372,46.649416,5.261820,1.631354e+09
std,23.169868,65.905279,10.120373,22.042513,40.586305,4.126131,2.216840e+02
min,-45.571200,-169.816700,40.730000,7.000000,0.000000,0.000000,1.631353e+09
25%,15.975000,-74.274100,63.790000,59.000000,1.000000,2.250000,1.631353e+09
50%,39.949500,-1.228600,70.920000,77.000000,40.000000,4.360000,1.631354e+09
75%,46.827350,19.661700,78.140000,88.000000,91.000000,7.440000,1.631354e+09
max,67.614200,153.400000,108.630000,100.000000,100.000000,22.370000,1.631354e+09

In [7]:
#A max temperature lower than 80 degrees but higher than 70.
#Wind speed less than 5 mph.
#Zero cloudiness.
#Humidity less than 50%

filter_df = cities_pd.loc[((cities_pd['Max Temp']<80) &
                                   (cities_pd['Max Temp']>70)) & 
                                   (cities_pd['Wind Speed']<5) & 
                          (cities_pd['Cloudiness']==0) &
                         (cities_pd['Humidity']<50)]

filter_df = filter_df.reset_index()

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
filter_df["Hotel Name"] = ""
hotel_df = pd.DataFrame(filter_df)
hotel_df.head()

,index,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,107,Lviv,49.8156,24.1297,71.55,49,0,2.24,UA,1631353448,
1,122,Vanderbijlpark,-26.6992,27.8356,74.95,17,0,4.23,ZA,1631353464,
2,272,Šumperk,49.9653,16.9707,77.34,40,0,4.25,CZ,1631353666,
3,322,Elin Pelin,42.6689,23.6025,79.68,43,0,3.44,BG,1631353723,
4,369,Pezinok,48.2667,17.2667,77.61,45,0,2.30,SK,1631353779,

In [12]:
params = {
    "radius": 5000,
    "types": "lodging",
    "keyword": "hotel",
    "key": g_key
}
for index, row in hotel_df.iterrows():
    # get lat, lng from df
    lat = row["Lat"]
    lng = row["Lng"]
    
    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    
    # Use the search term: "hotel" and our lat/lng
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # make request and print url
    name_address = requests.get(base_url, params=params)

    # convert to json
    name_address = name_address.json()
    
    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]['name']
        
    except (ValueError, IndexError):
        print(f" Index {index} Missing field/result... skipping.")

In [13]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

fig1 = gmaps.figure()

#Creating heatmap with labels and InfoWindow
heat_layer = gmaps.heatmap_layer(locations, weights=hotel_df['Humidity'], max_intensity = max_humidity,dissipating=False,point_radius=2)
fig1.add_layer(heat_layer)
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig1.add_layer(markers)

# Display figure
fig1

Figure(layout=FigureLayout(height='420px'))